version: '3'

services:
  hexagonal-node:
    build: ${SERVICE_PATH}
    container_name: 'hexagonal-node'
    image: 'hexagonal-node/test'
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${SERVICE_PATH}:${WORK_DIR}
    networks:
      - net-hexagonal
    depends_on:
      - 'mongodb'
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes:/data/db
    networks:
      - net-hexagonal
networks:
  net-hexagonal:
    driver: 'bridge'